# Generated by Django 5.1.3 on 2025-02-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='api_source_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('POL', 'Politics'), ('TECH', 'Technology'), ('BUS', 'Business'), ('SPO', 'Sports'), ('ENT', 'Entertainment')], default='GEN', max_length=50),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='source',
            field=models.CharField(choices=[('BBC', 'BBC News'), ('REU', 'Reuters'), ('TH', 'The Hindu'), ('WION', 'WION')], default='BBC', max_length=50),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(default='https://example.com'),
        ),
    ]
