# Generated by Django 5.1.3 on 2025-02-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsarticle_category_alter_newsarticle_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='source',
            field=models.CharField(choices=[('BBC', 'BBC News'), ('REU', 'Reuters'), ('TH', 'The Hindu'), ('WION', 'WION'), ('TOI', 'The Times of India'), ('NDTV', 'NDTV'), ('NEW_SOURCE', 'New Source Name')], default='BBC', max_length=50),
        ),
    ]
