# Generated by Django 5.1.3 on 2025-03-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsarticle_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='source',
            field=models.CharField(choices=[('BBC', 'BBC News'), ('REU', 'Reuters'), ('TH', 'The Hindu'), ('WION', 'WION'), ('TOI', 'The Times of India'), ('NDTV', 'NDTV')], default='BBC', max_length=50),
        ),
    ]
